/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

#include "main.h"

void Hardware_Config(void)
{
	SysClock_Config();
	SysTick_Config(100000);
	GPIO_Config();
	Interrupt_Config();
	TIM7_Config();
	UART2_Config();
	SPI1_Config();
	SPI3_Config();
	ADC1_Config();
}

/*
 * I2C1_Config();
 *
 * RTC_SET:
	DS3231_GetTime(I2C1, &time);
	if(time.year == 0)
	{
		time.sec = 0;
		time.min = 33;
		time.hour = 15;
		time.AM_PM_24H = 0;
		time.date = 16;
		time.day = 6;
		time.month = 7;
		time.year = 21;
		DS3231_SetTime(I2C1, &time);
	}
	DS3231_GetTime(I2C1, &time);

	RTC_Time time;
*/
/*
 * Test SPI: SPI1: Master - SPI3: Slaver
 *
 *
	uint8_t data[5] = {1, 2, 3, 4, 5};
	uint8_t datarv[5];
		SPI_CS_Enable();
		SPI_TransmitReceives(SPI1, SPI3, data, datarv, 4);
		SPI_CS_Disable();
		data[0]++;
		data[2]++;
 */

uint16_t adc_value[2];
uint8_t data[5] = {1, 2, 3, 4, 5};
uint8_t datarv[5];

int main(void)
{
	Hardware_Config();
	TIM6_Delay_ms(200);
	for(;;)
	{
		SPI_CS_Enable();
		SPI_TransmitReceives(SPI1, SPI3, data, datarv, 4);
		SPI_CS_Disable();
		data[0]++;
		data[2]++;
		GPIO_Toggle(LED3_Port, LED3_Pin);
		adc_value[0] = ADC1_GetValue(8);
		adc_value[1] = ADC1_GetValue(9);
		TIM6_Delay_ms(1000);
	}
}

void Delay_Cycle (uint32_t time)
{
	while (time --);
}

